sudo: false

language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
 - chmod +x gradlew

// install: ./gradlew setupCiWorkspace -S
install: ./gradlew setupDecompWorkspace -S
script: ./gradlew build -S

env:
  global:
    TERM=dumb

